hello: ENC[AES256_GCM,data:Xw906DMRGUgxy3QcIy4=,iv:eSSR6YzdoFcrOh/eg/VDXhGtjWE/fg5hslzOX1iYxNM=,tag:QREvtca6+uDAcJmfBi243Q==,type:str]
wireless.env: ENC[AES256_GCM,data:+5iuQGfzbS6E+kSPdgMPuotsX8tLjHS5rldJ4QevivGtIhGi5KSO+rmOlWPOFsJ1+4XQ10v4w3A1QBKZWeXJstG05SuPi8btTFZiY3u3GhYpQ55Ikavf2s7gIML3Owjh7J38bT8j0r8lUa9Lf94C9YsAnSZfl+ZwjkrSOu2tMtoSwVeknA+f/JZ3bTP5vYDki02YaRdYBUxH1m+E38HgexGuNWyZR9Z23gygZARibTbfz6dJzT+YyucQO0Unda4iL++B3sK1mAcYJbH/poEOewJI74aegVNgtH+nNfV8pd1bOczV5CQInhzK6E7tJ8mD5OQfGuFChRxMHM6JT+tQvJ+Pb/OGK0tk4GHLNWCik6WqJmGaphsbnC18OhiC2bbhEqzW70JeZqWc3ujslwt4dcUHaBPOUAcPLV8dBrd/EcMCj3Qk2173sw+pO04C2OMwNYwjyNGYTRvptIT1J+QFHNFPchAwXQrAiUSv0d481nepU406e1p/sRuA0l/k7CJX1dRln7M3G8XY/zGfZgnlob/pRG1VKPjn1kcI8sAFNJYl39y+16CZKiiAS8jANTMTlNHw5/yXcr2YAIooytJDWN7n4U9XwB9NGkPkPGT8YYO1Ysf1WxmGb7Dt5qxH6NJWSthqYJ0id0Hd/suknQ8qSJ+SgbIL90BEA4rzZEo9j9k778Cv0AZXISMrewdUOCzAEMRDVMhoP11oe5XVBD/dOJGtz7PmFxYWONoMYIKf516Yq49UwWnmsrGp9IG255FmAOgqCBmadmOi6xaSTTytYIbstpBkMCM5UAwu5X4M,iv:gGtHakGTbAg+H/FdvxR5NWjaKgky0jofXUz0QODXZlo=,tag:PkLa21XbKikPn13bJUe+zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age154cs0j8qhequ64uujls9dnrefnjm2973hrsf4gxvfunyrtml84gspljeq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eDJTajY0dlViV3EyUDVZ
            ZzdGUzJzTXhVWDVqbVFydml3cTY3b1FsblY4ClpreHd2UWxidXhrcUxPL25kZ1Za
            VzRmWUd6TXpRRFIrQWsxUGd6ZXAvWkUKLS0tIHZ3M1BDZXZBZWRzSUV1R2RMWVRG
            VTFqS1EzZzZ2dE8zMzFlTVhmdWh1SlkKnZPxNLiRKqTzsa3Q2XQABSRtyL5inmMM
            fjR6CYFYuH/btwUA7n33TmqFGrnnq8lf+sjbe+bQpQxoU2Yrksc+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T00:14:36Z"
    mac: ENC[AES256_GCM,data:j8PbShWSHexI3paQe/kOz2KY4YJjqkL8RgT5NoWGzh8IV/qY/WRXyyACgwkwalAAoScZuUHo1C7jLD2m6/qYO+/eeUPtqBurYuvSlNoxe7uNKV5+3ybq8krPaM6OqSZtyhS0ZMWDJ8HSZR0HsouFPQ0RiEXliUoXG1q7kOIH15Y=,iv:IXyJhY8Y7+EoEeiYJR4/NuLlh/q/wHDyEVd3GHUwU9Y=,tag:Q+xnVyMpg6NSUPBmP/DctA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
